version: '3.8'

services:
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres_db
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_HOST: ${POSTGRES_HOST}
  #     POSTGRES_DATABASE: ${POSTGRES_DATABASE}
  #   ports:
  #     - ${POSTGRES_HOST_PORT}:${POSTGRES_PORT}
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
  #     interval: 30s
  #     timeout: 60s
  #     retries: 5
  #     start_period: 80s
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_PORT}
    

  # backend:
  #   build:
  #     context: backend
  #     dockerfile: Dockerfile
  #   container_name: website
  #   env_file:
  #     - backend/.env
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     postgres:
  #       condition: service_healthy